[2024-04-05T22:41:52.331+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_osm_farmland.load_data_tobigquery manual__2024-04-05T22:36:41.245045+00:00 [queued]>
[2024-04-05T22:41:52.340+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_osm_farmland.load_data_tobigquery manual__2024-04-05T22:36:41.245045+00:00 [queued]>
[2024-04-05T22:41:52.341+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-05T22:41:52.355+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_data_tobigquery> on 2024-04-05 22:36:41.245045+00:00
[2024-04-05T22:41:52.361+0000] {standard_task_runner.py:60} INFO - Started process 1821 to run task
[2024-04-05T22:41:52.364+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_osm_farmland', 'load_data_tobigquery', 'manual__2024-04-05T22:36:41.245045+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/extract_file_data_from_osm.py', '--cfg-path', '/tmp/tmpg103cnp_']
[2024-04-05T22:41:52.366+0000] {standard_task_runner.py:88} INFO - Job 283: Subtask load_data_tobigquery
[2024-04-05T22:41:52.415+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_osm_farmland.load_data_tobigquery manual__2024-04-05T22:36:41.245045+00:00 [running]> on host 2adb4d880117
[2024-04-05T22:41:52.503+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_osm_farmland' AIRFLOW_CTX_TASK_ID='load_data_tobigquery' AIRFLOW_CTX_EXECUTION_DATE='2024-04-05T22:36:41.245045+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-05T22:36:41.245045+00:00'
[2024-04-05T22:43:17.809+0000] {logging_mixin.py:188} INFO - 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.; reason: invalid, message: Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 1; errors: 1; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: JSON parsing error in row starting at position 0: Nested arrays not allowed.
[2024-04-05T22:43:17.810+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-05T22:43:17.822+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=extract_osm_farmland, task_id=load_data_tobigquery, execution_date=20240405T223641, start_date=20240405T224152, end_date=20240405T224317
[2024-04-05T22:43:17.872+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-05T22:43:17.890+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
