[2024-04-01T14:57:10.624+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T14:57:07.646364+00:00 [queued]>
[2024-04-01T14:57:10.639+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T14:57:07.646364+00:00 [queued]>
[2024-04-01T14:57:10.640+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-01T14:57:10.667+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_farmland_from_api> on 2024-04-01 14:57:07.646364+00:00
[2024-04-01T14:57:10.676+0000] {standard_task_runner.py:60} INFO - Started process 2721 to run task
[2024-04-01T14:57:10.681+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_osm_farmland', 'load_farmland_from_api', 'manual__2024-04-01T14:57:07.646364+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/extract_file_data_from_osm.py', '--cfg-path', '/tmp/tmpppu0f5so']
[2024-04-01T14:57:10.683+0000] {standard_task_runner.py:88} INFO - Job 87: Subtask load_farmland_from_api
[2024-04-01T14:57:10.755+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T14:57:07.646364+00:00 [running]> on host 84497f327267
[2024-04-01T14:57:10.929+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_osm_farmland' AIRFLOW_CTX_TASK_ID='load_farmland_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T14:57:07.646364+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T14:57:07.646364+00:00'
[2024-04-01T14:57:32.623+0000] {collection.py:293} WARNING - Skipping field nodes: invalid type 13
[2024-04-01T14:57:37.594+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_file_data_from_osm.py", line 69, in load_farmland_from_api
    upload_geodataframe_to_gcs(farm_gdf, GCS_BUCKET, GCS_INTERMEDIATE_PATH)
  File "/opt/airflow/dags/utils.py", line 15, in upload_geodataframe_to_gcs
    geojson_bytes = geodataframe.to_file(index=False,Driver='GeoJSON').encode('latin-1')  # Consider compression if needed
TypeError: to_file() missing 1 required positional argument: 'filename'
[2024-04-01T14:57:37.611+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_osm_farmland, task_id=load_farmland_from_api, execution_date=20240401T145707, start_date=20240401T145710, end_date=20240401T145737
[2024-04-01T14:57:37.627+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 87 for task load_farmland_from_api (to_file() missing 1 required positional argument: 'filename'; 2721)
[2024-04-01T14:57:37.662+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T14:57:37.689+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
