[2024-04-01T14:45:24.961+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T14:40:54.503294+00:00 [queued]>
[2024-04-01T14:45:24.969+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T14:40:54.503294+00:00 [queued]>
[2024-04-01T14:45:24.970+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-01T14:45:24.984+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): load_farmland_from_api> on 2024-04-01 14:40:54.503294+00:00
[2024-04-01T14:45:24.991+0000] {standard_task_runner.py:60} INFO - Started process 2544 to run task
[2024-04-01T14:45:24.994+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_osm_farmland', 'load_farmland_from_api', 'manual__2024-04-01T14:40:54.503294+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/extract_file_data_from_osm.py', '--cfg-path', '/tmp/tmpx_k19bvu']
[2024-04-01T14:45:24.996+0000] {standard_task_runner.py:88} INFO - Job 84: Subtask load_farmland_from_api
[2024-04-01T14:45:25.047+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_osm_farmland.load_farmland_from_api manual__2024-04-01T14:40:54.503294+00:00 [running]> on host 84497f327267
[2024-04-01T14:45:25.130+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_osm_farmland' AIRFLOW_CTX_TASK_ID='load_farmland_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T14:40:54.503294+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T14:40:54.503294+00:00'
[2024-04-01T14:45:45.302+0000] {collection.py:293} WARNING - Skipping field nodes: invalid type 13
[2024-04-01T14:45:48.065+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_file_data_from_osm.py", line 69, in load_farmland_from_api
    upload_geodataframe_to_gcs(farm_gdf, GCS_BUCKET, GCS_INTERMEDIATE_PATH)
  File "/opt/airflow/dags/utils.py", line 9, in upload_geodataframe_to_gcs
    storage_client = storage.Client.from_service_account_json(json_credentials_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/client/__init__.py", line 106, in from_service_account_json
    with io.open(json_credentials_path, "r", encoding="utf-8") as json_fi:
FileNotFoundError: [Errno 2] No such file or directory: '/key/data-enginerring-zoomcamp-b8719aa4a43e.json'
[2024-04-01T14:45:48.083+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=extract_osm_farmland, task_id=load_farmland_from_api, execution_date=20240401T144054, start_date=20240401T144524, end_date=20240401T144548
[2024-04-01T14:45:48.097+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 84 for task load_farmland_from_api ([Errno 2] No such file or directory: '/key/data-enginerring-zoomcamp-b8719aa4a43e.json'; 2544)
[2024-04-01T14:45:48.147+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T14:45:48.173+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
